export const Issues = {
    GENERAL_MEDICINE: "Fever",
    CARDIOLOGY: "Hypertension",
    ENDOCRINOLOGY: "Diabetes",
    GASTROENTEROLOGY: "Gastritis",
    HEMATOLOGY: "Anemia",
    INFECTIOUS_DISEASE: "Flu",
    NEPHROLOGY: "Kidney Stones",
    NEUROLOGY: "Migraine",
    ONCOLOGY: "Breast Cancer",
    OPHTHALMOLOGY: "Cataracts",
    ORTHOPEDICS: "Fractures",
    OTOLARYNGOLOGY: "Sinusitis",
    PEDIATRICS: "Common Cold",
    PSYCHIATRY: "Depression",
    PULMONOLOGY: "Asthma",
    RADIOLOGY: "X-ray",
    UROLOGY: "Kidney Stones",
    OBSTETRICS_AND_GYNECOLOGY: "Pregnancy",
    SURGERY: "Appendectomy",
    ANESTHESIOLOGY: "Anesthesia Complications",
    PATHOLOGY: "Biopsy",
    RHEUMATOLOGY: "Rheumatoid Arthritis",
    PHYSICAL_MEDICINE_AND_REHABILITATION: "Physical Therapy",
    ALLERGY_AND_IMMUNOLOGY: "Allergic Rhinitis",
    GERIATRICS: "Dementia",
    CRITICAL_CARE_MEDICINE: "Respiratory Failure",
    ENDOCRINE_SURGERY: "Thyroid Surgery",
    PAIN_MANAGEMENT: "Chronic Pain",
    GENETICS: "Genetic Disorders"
};
